-- Fix categories table ID to be Auto-Incrementing (Identity)
-- The error "null value in column id violates not-null constraint" happens because the DB 
-- isn't generating the ID automatically.

DO $$
BEGIN
    -- 1. Try to make it an Identity column
    BEGIN
        ALTER TABLE categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION WHEN duplicate_column OR others THEN
        -- If it already has identity or fails, ignore or try legacy sequence
        RAISE NOTICE 'Identity already exists or failed, checking sequence...';
    END;

    -- 2. Sync the sequence to the current maximum ID to avoid collisions
    -- This handles cases where manual IDs were inserted (1, 2, 50...)
    -- We use dynamic SQL to avoid errors if the sequence doesn't auto-link yet
    DECLARE
        max_id BIGINT;
    BEGIN
        SELECT COALESCE(MAX(id), 0) + 1 INTO max_id FROM categories;
        
        -- Try to update the identity sequence
        PERFORM setval(pg_get_serial_sequence('categories', 'id'), max_id, false);
    EXCEPTION WHEN OTHERS THEN
        -- Fallback: If pg_get_serial_sequence returns null/error, maybe manual sequence?
        NULL; 
    END;
END $$;
